### ISSUE TITLE
Feat.: mutable org labels

### ISSUE THREAD

**Issue by QSmally** [RedCMD/QCPU-Syntax-Highlighter#10]
The QCPU CLI implements an optional closure to specify the override address / new pointer location.

A label can be defined like `.label(anybaseint):`, with `anybaseint` being something like:

* `0b00001010` (binary, any bitcount is possible)
* `0x0A` (hexadecimal)
* `10` (decimal)

It's optional, so `.label:` is still possible (but *not* empty: `.label():`)

**Comment by RedCMD** [comment]
Is `.&label(0x0A):` allowed?

**Comment by QSmally** [comment]
Yes, my bad for not including it in an example
