### ISSUE TITLE
Bug: incorrect indentation

### ISSUE THREAD

**Issue by QSmally** [RedCMD/QCPU-Syntax-Highlighter#11]
If I insert a label as a separate line and press enter, an indentation is automatically formed, while it's not suffixed by `:` (because it's not a label definition, rather using an existing label). It does not happen when I put the label on the same line like `CPS`, with a comma separating them, such as `CPS, .@return_label`. See the video for reference:

https://user-images.githubusercontent.com/38661077/152567266-db1bcc53-8916-42b3-a516-94b2746a0a14.mp4

**Comment by RedCMD** [comment]
You don't want it to indent on existing labels?

**Comment by QSmally** [comment]
A new indentation layer should be created after you defined a `.label:`, and not when you're using a `.label` (which is shown in the video). In the video, the creation of `.@return_label:` is irrelevant. A working example:

```asm
JMP 0
.some_label
; using a label, not defining anything
AST 0
.some_label:
    ; created a label, indented
    AST 0
```

**Comment by RedCMD** [comment]
Line indenter now checks for `:` at the end of a `.label`
https://github.com/RedCMD/QCPU-Syntax-Highlighter/commit/13ceed025e8dd549b1ff983ac3d341c4bc9026ee
